name: 'Build a deb package'
description: 'Build a deb (Ubuntu, Debian) package'

inputs:
  LOCAL:
    description: "Append +LOCAL to package revision"
    required: false

runs:
  using: docker
  image: Dockerfile
  env:
    LOCAL: ${{ inputs.LOCAL }}

branding:
  icon: package
  color: gray-dark
